/**
 * BVH Manager — wraps WASM module lifecycle and bridges to GPU buffers.
 */
import { BufferManager } from '../gpu/buffer-manager';

// Type for the WASM module exports (generated by wasm-pack)
export interface WasmCwBvhInstance {
  nodes_ptr(): number;
  nodes_byte_len(): number;
  nodes_count(): number;
  indices_ptr(): number;
  indices_byte_len(): number;
  indices_count(): number;
  triangles_ptr(): number;
  triangles_byte_len(): number;
  triangles_count(): number;
  total_aabb(): Float32Array;
  build_time_ms(): number;
  rebuild(quality: number): void;
  convert_bvh2_to_cwbvh(): void;
  insert_triangle(
    v0x: number, v0y: number, v0z: number,
    v1x: number, v1y: number, v1z: number,
    v2x: number, v2y: number, v2z: number
  ): number;
  remove_triangle(prim_id: number): void;
  resize_primitive(
    prim_id: number,
    min_x: number, min_y: number, min_z: number,
    max_x: number, max_y: number, max_z: number
  ): void;
  reinsert_primitive(prim_id: number): void;
  batch_update_and_reinsert(prim_ids: Uint32Array, aabbs_flat: Float32Array): void;
  partial_rebuild(prim_ids: Uint32Array, aabbs_flat: Float32Array): void;
  refit_all(): void;
  free(): void;
}

export interface WasmModule {
  WasmCwBvh: {
    new(triangles: Float32Array, quality: number, keepBvh2: boolean): WasmCwBvhInstance;
  };
  wasm_memory(): WebAssembly.Memory;
  BuildQuality: {
    Fastest: number;
    Fast: number;
    Medium: number;
    Slow: number;
    VerySlow: number;
  };
}

export enum BuildQuality {
  Fastest = 0,
  Fast = 1,
  Medium = 2,
  Slow = 3,
  VerySlow = 4,
}

export class BvhManager {
  private wasmModule: WasmModule | null = null;
  private bvh: WasmCwBvhInstance | null = null;

  /** Statistics from the last build */
  public lastBuildTimeMs: number = 0;
  public nodeCount: number = 0;
  public triangleCount: number = 0;

  /**
   * Load and initialize the WASM module.
   */
  async init(): Promise<void> {
    // Import the wasm-pack generated module
    const mod = await import('../wasm/pkg/obvhs_wasm.js');
    await mod.default(); // Initialize WASM
    this.wasmModule = mod as unknown as WasmModule;
  }

  /**
   * Build a CWBVH from triangle data.
   * @param triangles Flat Float32Array: every 9 floats = 1 triangle (3 vertices × xyz)
   * @param quality Build quality preset
   * @param keepBvh2 Whether to keep BVH2 for dynamic operations
   */
  buildCwBvh(
    triangles: Float32Array,
    quality: BuildQuality = BuildQuality.Medium,
    keepBvh2: boolean = false
  ): void {
    if (!this.wasmModule) throw new Error('WASM module not loaded');

    // Free previous BVH
    this.bvh?.free();
    this.bvh = new this.wasmModule.WasmCwBvh(triangles, quality, keepBvh2);

    this.lastBuildTimeMs = this.bvh.build_time_ms();
    this.nodeCount = this.bvh.nodes_count();
    this.triangleCount = this.bvh.triangles_count();
  }

  /**
   * Upload BVH data to GPU buffers.
   */
  uploadToGpu(bufferManager: BufferManager): {
    nodes: GPUBuffer;
    indices: GPUBuffer;
    triangles: GPUBuffer;
  } {
    if (!this.bvh || !this.wasmModule) {
      throw new Error('No BVH built yet');
    }

    const memory = this.wasmModule.wasm_memory();

    const nodes = bufferManager.uploadFromWasm(
      'bvh_nodes',
      memory,
      this.bvh.nodes_ptr(),
      this.bvh.nodes_byte_len()
    );

    const indices = bufferManager.uploadFromWasm(
      'primitive_indices',
      memory,
      this.bvh.indices_ptr(),
      this.bvh.indices_byte_len()
    );

    const triangles = bufferManager.uploadFromWasm(
      'triangles',
      memory,
      this.bvh.triangles_ptr(),
      this.bvh.triangles_byte_len()
    );

    return { nodes, indices, triangles };
  }

  /**
   * Rebuild the CWBVH (full rebuild).
   */
  rebuild(quality: BuildQuality = BuildQuality.Medium): void {
    if (!this.bvh) throw new Error('No BVH built yet');
    this.bvh.rebuild(quality);
    this.lastBuildTimeMs = this.bvh.build_time_ms();
    this.nodeCount = this.bvh.nodes_count();
  }

  /**
   * Convert BVH2 to CWBVH after dynamic updates.
   */
  convertBvh2ToCwbvh(): void {
    if (!this.bvh) throw new Error('No BVH built yet');
    this.bvh.convert_bvh2_to_cwbvh();
    this.nodeCount = this.bvh.nodes_count();
  }

  /**
   * Get the total AABB of the BVH.
   */
  getTotalAabb(): { min: [number, number, number]; max: [number, number, number] } {
    if (!this.bvh) throw new Error('No BVH built yet');
    const aabb = this.bvh.total_aabb();
    return {
      min: [aabb[0], aabb[1], aabb[2]],
      max: [aabb[3], aabb[4], aabb[5]],
    };
  }

  /**
   * Get the underlying WASM BVH instance (for advanced use).
   */
  get instance(): WasmCwBvhInstance | null {
    return this.bvh;
  }

  /**
   * Cleanup.
   */
  destroy(): void {
    this.bvh?.free();
    this.bvh = null;
  }
}
